name: Canary update config.yaml

on:
  workflow_run:
    workflows: ["Deploy config.yaml global via OIDC"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  canary-update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::323228886994:role/pipeline-oicd
          aws-region: us-east-2

      - name: Instalar dependências
        run: |
          pip install boto3 pyyaml

      - name: Executar script de merge
        run: python merge_canary.py
