name: Atualizar Configs Canary

on:
  workflow_dispatch:
  push:
    paths:
      - config-global.yaml
      - canary_clients.json

permissions:
  id-token: write
  contents: read

jobs:
  canary-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::323228886994:role/pipeline-oicd
          aws-region: us-east-2

      - name: Instalar dependências
        run: |
          pip install boto3 pyyaml deepmerge

      - name: Executar script de merge
        run: python merge_configs.py
