name: Deploy Manual Global (todos os clientes)

on:
  workflow_dispatch:  # <- ativação manual no GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  deploy-global:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::323228886994:role/pipeline-oicd
          aws-region: us-east-2

      - name: Instalar dependências
        run: |
          pip install boto3 pyyaml

      - name: Executar deploy completo
        run: python deploy_geral.py
